name: Refresh Service Observability Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  job1:
    uses: getyourguide/monitoring-refresh/.github/workflows/refresh-monitoring.yml@master
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
